version: "3.7"

services:
  nginx-client:
    restart: always
    container_name: nginx-client
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts: "host.docker.internal:host-gateway"
    ports:
      - "80:80"